### ISSUE TITLE
Athena Pro - Jumbotron Slider 

### ISSUE THREAD

**Issue by BOOLSAI** [smartcatdev/Smartcat-support-ticket-system#1]
After a WP Update my Athena Pro Jumbotron sliders seem to be lost. I am trying to figure out how to restore them, including restoring backups using UpdraftPlus, but no avail.

The site I am having problems with you can find [here](http://www.kickboxing-sakura.nl).

Can anyone please help me? 😉

**Comment by BOOLSAI** [comment]
Might this be a compatibility issue?? How to solve it?

**Comment by smartcatdev** [comment]
FYI cant see the site as it's behind the WP Construction mode screen.

http://athena.smartcatdev.wpengine.com/ is running the latest version of WP ( updated this morning ) WP4.7.2 and it's fully compatible.

**Comment by smartcatdev** [comment]
@BOOLSAI for further support with Athena Pro, please contact us directly from our website. This repo is not frequently monitored. https://smartcatdesign.net/get-support/
